# 📊 DATA INGESTION SERVICE - KUBERNETES DEPLOYMENT
# High-throughput market data processing with stream handling

apiVersion: apps/v1
kind: Deployment
metadata:
  name: data-service
  namespace: trading
  labels:
    app: data-service
    tier: data
    version: v1
spec:
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  selector:
    matchLabels:
      app: data-service
  template:
    metadata:
      labels:
        app: data-service
        tier: data
        version: v1
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "8080"
        prometheus.io/path: "/metrics"
    spec:
      containers:
      - name: data-service
        image: trading/data-service:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080
          name: http
        - containerPort: 8081
          name: metrics
        env:
        - name: POSTGRES_HOST
          value: "postgres-service"
        - name: REDIS_HOST
          value: "redis-service"
        - name: KAFKA_BROKERS
          value: "kafka-service:9092"
        - name: ALPHA_VANTAGE_API_KEY
          valueFrom:
            secretKeyRef:
              name: api-secrets
              key: alpha-vantage-key
        - name: POLYGON_API_KEY
          valueFrom:
            secretKeyRef:
              name: api-secrets
              key: polygon-key
        - name: MARKET_HOURS_START
          value: "09:30"
        - name: MARKET_HOURS_END
          value: "16:00"
        - name: LOG_LEVEL
          value: "INFO"
        - name: JAEGER_AGENT_HOST
          value: "jaeger-agent"
        resources:
          requests:
            memory: "1Gi"
            cpu: "500m"
          limits:
            memory: "2Gi"
            cpu: "1000m"
        volumeMounts:
        - name: data-storage
          mountPath: /app/data
        livenessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /ready
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 5
          timeoutSeconds: 3
          failureThreshold: 2
        securityContext:
          runAsNonRoot: true
          runAsUser: 1000
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: true
          capabilities:
            drop:
            - ALL
      volumes:
      - name: data-storage
        persistentVolumeClaim:
          claimName: data-storage-pvc
      securityContext:
        fsGroup: 1000

---
apiVersion: v1
kind: Service
metadata:
  name: data-service
  namespace: trading
  labels:
    app: data-service
spec:
  type: ClusterIP
  ports:
  - port: 8080
    targetPort: 8080
    protocol: TCP
    name: http
  - port: 8081
    targetPort: 8081
    protocol: TCP
    name: metrics
  selector:
    app: data-service

---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: data-service-hpa
  namespace: trading
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: data-service
  minReplicas: 2
  maxReplicas: 6
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 80

---
apiVersion: v1
kind: Secret
metadata:
  name: api-secrets
  namespace: trading
type: Opaque
data:
  # Base64 encoded API keys - REPLACE WITH ACTUAL VALUES
  alpha-vantage-key: WUVF1UkFQSSyS0VZLVBMQUNFSE9MREVS  # YOUR_API_KEY placeholder
  polygon-key: WUVF1UkFQSSyS0VZLVBMQUNFSE9MREVS  # YOUR_API_KEY placeholder
