# ⚡ EXECUTION SERVICE - KUBERNETES DEPLOYMENT
# Order execution with smart routing and latency optimization

apiVersion: apps/v1
kind: Deployment
metadata:
  name: execution-service
  namespace: trading
  labels:
    app: execution-service
    tier: critical
    version: v1
spec:
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  selector:
    matchLabels:
      app: execution-service
  template:
    metadata:
      labels:
        app: execution-service
        tier: critical
        version: v1
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "8080"
        prometheus.io/path: "/metrics"
    spec:
      containers:
      - name: execution-service
        image: trading/execution-service:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080
          name: http
        - containerPort: 8081
          name: metrics
        env:
        - name: POSTGRES_HOST
          value: "postgres-service"
        - name: REDIS_HOST
          value: "redis-service"
        - name: KAFKA_BROKERS
          value: "kafka-service:9092"
        - name: ALPACA_API_KEY
          valueFrom:
            secretKeyRef:
              name: broker-secrets
              key: alpaca-api-key
        - name: ALPACA_SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: broker-secrets
              key: alpaca-secret-key
        - name: ALPACA_BASE_URL
          value: "https://paper-api.alpaca.markets"  # Paper trading URL
        - name: MAX_ORDER_SIZE_USD
          value: "10000"
        - name: ORDER_TIMEOUT_SECONDS
          value: "30"
        - name: SLIPPAGE_TOLERANCE_BPS
          value: "20"
        - name: LOG_LEVEL
          value: "INFO"
        - name: JAEGER_AGENT_HOST
          value: "jaeger-agent"
        resources:
          requests:
            memory: "512Mi"
            cpu: "300m"
          limits:
            memory: "1Gi"
            cpu: "600m"
        livenessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /ready
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 5
          timeoutSeconds: 3
          failureThreshold: 2
        securityContext:
          runAsNonRoot: true
          runAsUser: 1000
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: true
          capabilities:
            drop:
            - ALL
      securityContext:
        fsGroup: 1000
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: app
                operator: In
                values:
                - execution-service
            topologyKey: kubernetes.io/hostname

---
apiVersion: v1
kind: Service
metadata:
  name: execution-service
  namespace: trading
  labels:
    app: execution-service
spec:
  type: ClusterIP
  ports:
  - port: 8080
    targetPort: 8080
    protocol: TCP
    name: http
  - port: 8081
    targetPort: 8081
    protocol: TCP
    name: metrics
  selector:
    app: execution-service

---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: execution-service-hpa
  namespace: trading
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: execution-service
  minReplicas: 2
  maxReplicas: 4
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 80

---
apiVersion: v1
kind: Secret
metadata:
  name: broker-secrets
  namespace: trading
type: Opaque
data:
  # Base64 encoded broker API keys - REPLACE WITH ACTUAL VALUES
  alpaca-api-key: WUVF1UkFQSSyS0VZLVBMQUNFSE9MREVS  # YOUR_API_KEY placeholder
  alpaca-secret-key: WUVF1UkFQSSyS0VZLVBMQUNFSE9MREVS  # YOUR_SECRET_KEY placeholder

---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: execution-service-pdb
  namespace: trading
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app: execution-service
